spring.application.name=springai-mcp-server

server.port=8081

spring.ai.mcp.server.enabled=true
spring.ai.mcp.server.stdio=true
spring.main.banner-mode=off
logging.pattern.console=
logging.level.root=off